### PR TITLE
Inherit OS stdio in curl command

### LINKED ISSUE #146: curl stdout goes to oauth2l stderr
In curl.go, the output of the `curl` command gets fed into Go's `print`:

https://github.com/google/oauth2l/blob/2105d6b0f3781e4ef97e1dd9c513f636dd721982/util/curl.go#L42

but that sends it to stderr, and it's not considered all that stable:

https://github.com/golang/go/blob/db36eca33c389871b132ffb1a84fd534a349e8d8/src/builtin/builtin.go#L265-L269

Isn't `oauth2l curl` mostly supposed to be a drop-in wrapper for `curl`? If so, I would expect the invocation to inherit the program's channels so that stdout and stderr can use streaming. Similarly, this would presumably also unlock streaming stdin for POST and friends.

Additionally, the previous statement writes any errors to stdout, so the channels are in fact getting swapped. This is confusing, no?

### PR DESCRIPTION
**Pull request by timdp**
Fixes #146.

### CODE REVIEW

**Comment by timdp** [comment]
Apologies for the force-pushes. I thought I needed to change the email address on the commit to have the CLA check pick up on it.

**Review by andyrzhao — CHANGES_REQUESTED** [review]
Thanks for this PR! I think the cli_test needs some small updates to run curl in silent mode (-s) so it doesn't print out the progress. I'm curious as to why it didn't show up in the output buffer before though?

**Comment by timdp** [comment]
Oh, sorry. When `go test` didn't do anything, I assumed there were no tests, but I should have checked the `Makefile` or `integration` folder.

I've added `-s` to the `curl` command in the tests to re-match stdout with the snapshots. Test are passing again now.

Alternatively, I suppose we could inspect curl's default output, but that would also involve normalizing the URL and progress bar before snapshotting.

**Review by andyrzhao — APPROVED** [review]

**Comment by DavidDTA** [comment]
This was merged almost 2 years ago, but there has been no release since then to make it available. Is there any chance a new release could be created?

**Comment by andyrzhao** [comment]
Yes, I can try to push out updated releases for all platforms. ETA end of this year at the latest.

**Pull request merged**
